### ISSUE TITLE
TwilightChat Server Core - MIlestone 1

### ISSUE THREAD

**Issue by pi19044** [twilightchat/server#1]
- [X] Types
  - [X] Emoji
  - [X] Invite
  - [X] Message
  - [X] Discriminator
  - [X] Snowflake
  - [X] Role tag
  - [X] Role
  - [X] Channel
  - [X] User
  - [X] Guild
  - [X] Guild member
  - [X] Sticker

- [ ] Routes
  - [X] `api/v8/auth/login`
  - [X] `api/v8/auth/register`
  - [X] `api/v8/channels/<channel_id>/messages`
  - [X] `api/v8/gateway`
  - [ ] `api/v8/guilds`
    - [ ] `api/v8/guilds/<guild_id>`
      - [ ] `api/v8/guilds/<guild_id>/invites`
      - [ ] `api/v8/guilds/<guild_id>/template`
        - [ ]  `api/v8/guilds/<guild_id>/template/<template_code>`
      - [ ] `api/v8/guilds/<guild_id>/widget`
        - [ ] `api/v8/guilds/<guild_id>/widget.png`
      - [ ] `api/v8/guilds/<guild_id>/channels`
      - [ ] `api/v8/guilds/<guild_id>/roles`
        - [ ] `api/v8/guilds/<guild_id>/roles/<role_id>`
      - [ ]  `api/v8/guilds/<guild_id>/bans`
      - [ ] `api/v8/guilds/<guild_id>/members`

**Comment by pi19044** [comment]
any more routes should i add?
